# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               BuildOurOwnRepublic
tagline:             'blog rpblic'
description:         'blog of <a href="https://github.com/rpblic" target="_blank">rpblic</a>, gyumin, sim. Lanyon jekyll theme Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 rpblic.github.io
baseurl:             'https://rpblic.github.io'
paginate:            3

# About/contact
author:
  name:              rpblic
  githuburl:         https://github.com/rpblic
  fburl:             https://facebook.com/rpblic.gyuminsim
  email:             rbals1218@gmail.com

# Custom vars
version:             1.0.0
