# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               BuildOurOwnRepublic
tagline:             'blog rpblic'
description:         'blog of <a href="https://github.com/rpblic" target="_blank">rpblic</a>, gyumin, sim. Lanyon jekyll them Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 rpblic.github.io
baseurl:             'https://rpblic.github.io'
paginate:            3
excerpt_separator: <!-- more -->

# About/contact
author:
  name:              rpblic
  url:               https://github.com/rpblic
  email:             rbals1218@gmail.com

# Custom vars
version:             1.0.0

# Collections
collections:
  docs:
    output: true
    defaults:
      scope:
        path: ""
        type: docs
      values:
        layout: docc
